### ISSUE TITLE
DRE needs an About page

### ISSUE THREAD

**Issue by darctur** [gespinoza/datarodsexplorer#13]
This is different from the Readme.md file; would be accessible from the DRE application. This would explain the context for DRE for users; where to go for user / developer guide; provide acknowledgement for NASA funding and Gonzalo's authorship. We should be careful about putting any contact info on this page, it would likely result in much spam being received.

**Comment by gespinoza** [comment]
Can you write the paragraphs and info? and afterwards I'll add the page.

**Comment by darctur** [comment]
I've asked Shawn to change the DRE Exit button at top-right to be an About button. I'll assemble the docs in MD format, and make ready for ReadTheDocs setup.
