### ISSUE TITLE
Received GRACE data rod URLs 

### ISSUE THREAD

**Issue by darctur** [gespinoza/datarodsexplorer#14]
URLs for 3 variables just received from Bill Teng/Richard Strub. Do we have all the background and reference material needed for these?

Root zone soil moisture percentile:
http://hydro1.sci.gsfc.nasa.gov/daac-bin/access/timeseries.cgi?variable=GRACE:GRACEDADM_CLSM025NA_7D.1:rtzsm_inst&startDate=2012-08-04T07&endDate=2015-09-05T00&location=GEOM:POINT%28-112.3,%2030.4%29&type=plot

Surface soil moisture percentile: 
http://hydro1.sci.gsfc.nasa.gov/daac-bin/access/timeseries.cgi?variable=GRACE:GRACEDADM_CLSM025NA_7D.1:sfsm_inst&startDate=2012-08-04T07&endDate=2015-09-05T00&location=GEOM:POINT%28-112.3,%2030.4%29&type=plot

Groundwater percentile:
http://hydro1.sci.gsfc.nasa.gov/daac-bin/access/timeseries.cgi?variable=GRACE:GRACEDADM_CLSM025NA_7D.1:gws_inst&startDate=2012-08-04T07&endDate=2015-09-05T00&location=GEOM:POINT%28-112.3,%2030.4%29&type=plot

**Comment by gespinoza** [comment]
The web services are now on the web app.
