### ISSUE TITLE
Menu button (upper-left corner) not fully displayed

### ISSUE THREAD

**Issue by pjruess** [gespinoza/datarodsexplorer#17]
Menu button (three horizontal, parallel lines in upper left) is not fully displayed; the image is cut off by the edge of the screen. See attached image. 

![image](https://cloud.githubusercontent.com/assets/17786508/13925492/7622fd96-ef56-11e5-9fc2-268bf6a7266e.png)

**Comment by pjruess** [comment]
Consider renaming the left-hand side to say "Map" (similar to the "Time Series" label in the bottom half). "Product Model" seems like it should be more of a sub-category, not a header.

**Comment by darctur** [comment]
Cleaning up old bugs. This one was fixed by revisions to code in dev-shawn branch.
