### ISSUE TITLE
"Year-on-year changes" 1979 and 2016 issues for NLDAS/GLDAS/TRMM

### ISSUE THREAD

**Issue by pjruess** [gespinoza/datarodsexplorer#19]
- NLDAS: selecting 1979 causes an error
- NLDAS: selecting 2016 creates a plots, but the 2016 data is absent (no partial data)
- GLDAS: selecting 1979 or 2016 create plots, but the 1979 and 2016 data is absent (no partial data)
- TRMM: selecting 1979 and/or 2016 causes an error

**Comment by darctur** [comment]
related to #28, but for different controller section

**Comment by darctur** [comment]
Cleaning up old bugs. This one was fixed by revisions to code in dev-shawn branch.
