### ISSUE TITLE
DRE app should reveal what time ranges are available for each product/variable

### ISSUE THREAD

**Issue by darctur** [gespinoza/datarodsexplorer#24]
These are posted in the user docs, but need to be exposed on the DRE layout. Add StartDate and EndDate values for each product/variable in the data table. 

How to keep the data table end-date current? Could set chron job to query data servers info page, and update the DRE variable table def columns.

**Comment by pjruess** [comment]
FYI, sample code for the Datepicker Gonzalo used: 
https://tethys-platform.readthedocs.org/en/1.1.0/tethys_sdk/gizmos_api.html#date-picker

**Comment by pjruess** [comment]
[BeautifulSoup](https://www.crummy.com/software/BeautifulSoup/bs4/doc/) webpage scraper; could use this to locate start/end dates on this [NASA webpage](http://mirador.gsfc.nasa.gov/cgi-bin/mirador/servcoll.pl?helpmenuclass=inventory&SearchButton=Search%20GES-DISC). 

Here's a [tutorial](http://journalistsresource.org/tip-sheets/research/python-scrape-website-data-criminal-justice).

**Comment by darctur** [comment]
Cleaning up old bugs. This one was fixed by revisions to code in dev-shawn branch.
