### ISSUE TITLE
WMS performance improvement: local caching

### ISSUE THREAD

**Issue by darctur** [gespinoza/datarodsexplorer#3]
Need ways to improve performance of screen display. One way would be for the WMS request to ask for larger extent than being displayed in the DRE map frame. This would allow user to pan a little in any direction, and zoom in/out a little, without requiring a new WMS request. Would like to try asking for an extent 3x wider and taller than (and centered on) the current view frame, which would allow the user to pan or zoom a whole step. 

Would also like to explore local caching of any display screens received, and using them before sending a new WMS request. There's probably some practices and algorithms available for doing this.

**Comment by gespinoza** [comment]
I think that the users have to select the correct extent desired before hitting 'display map'. If we get a raster 3x larger than the extent, it diminish the use of the map extent and the ability of querying and subseting the data.

Local caching will require an additional computing effort on the Hydroshare server and it will increase significantly response and drawing times. The DRE is a visualization app, if we want to include image processing, performance will decrease significantly. I think that if we want to improve response, those efforts should be done at the NASA servers.
