### ISSUE TITLE
Once "Plot one variable" is selected, the other plotting options are no longer visible. Scrolling down is not intuitive. 

### ISSUE THREAD

**Issue by pjruess** [gespinoza/datarodsexplorer#32]
When "Plot one variable" is selected, the two options for "Compare two variables" and "Year-on-year changes" are pushed off-screen. It is not obvious that these options are still available unless you scroll down (and this is not necessarily intuitive). Should reduce font size or enable scroll bar in order to make this more obvious. 
![image](https://cloud.githubusercontent.com/assets/17786508/14321431/c29abdb4-fbde-11e5-97e7-ef261c093574.png)

**Comment by darctur** [comment]
Cleaning up old bugs. This one was fixed by revisions to code in dev-shawn branch.
