### ISSUE TITLE
Loading screen

### ISSUE THREAD

**Issue by pjruess** [gespinoza/datarodsexplorer#33]
Should have a loading update in the form of a pop-up on top of the map (see below), so that user knows map is being processed. 

![image](https://cloud.githubusercontent.com/assets/17786508/14321544/43ccfcc6-fbdf-11e5-8066-455c4fb4101a.png)

Image and sample code available here: https://css-tricks.com/snippets/jquery/display-loading-graphic-until-page-fully-loaded/

**Comment by darctur** [comment]
Cleaning up old bugs. This one was fixed by revisions to code in dev-shawn branch.
