### ISSUE TITLE
Organize main.js and controllers.py, divide into multiple files

### ISSUE THREAD

**Issue by darctur** [gespinoza/datarodsexplorer#6]
Gonzalo says this is in progress; see the branch 'gonzalo_dev' on the github repository.

**Comment by gespinoza** [comment]
The main.js script was divided into five scripts: 
- main.js
- custom_plots.js
- load_pages.js
- model_objects.js
- on_change.js

The controllers.py was divided in two scripts:
- controllers.py
- model_objects.py

Comments and descriptions on each script are still missing. Notice that the two model_objects scripts (.py and .js) now hold all the info of the WMS and data rods weres services such as GRACE, NLDAS, TRMM, etc. These two scripts can be expanded to include more services.

Note: The gonzalo_dev branch was merged into master.
