### ISSUE TITLE
units-of-measure typos in variable pulldown

### ISSUE THREAD

**Issue by darctur** [gespinoza/datarodsexplorer#8]
NLDAS “Surface Runoff” units - change from kg/m^2 to kg/m^2/s
GLDAS “Precipitation Rate” units - change from kg/m^s/hr to kg/m^2/hr

**Comment by pjruess** [comment]
Oops! NLDAS runoff units are correct: http://disc.gsfc.nasa.gov/hydrology/data-holdings/parameters/surface_runoff.shtml. 

I fixed GLDAS units and will test a commit with Gonzalo.
